name: grassorots
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  bluetooth_low_energy: ^6.1.0
  ble_peripheral: ^2.4.0
  permission_handler: ^11.3.0
  logging: ^1.3.0
  sqflite: ^2.4.1
  path: ^1.9.0
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
